# --------------------------------------------------
# Server
# --------------------------------------------------

server.port=8080

# --------------------------------------------------
# Database
# --------------------------------------------------

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://db:3306/intranet_tools?useSSL=false&autoReconnect=true&serverTimezone=CET&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=uJ7$gT9vLp@3rZ!wQx1m

# --------------------------------------------------
# JPA
# --------------------------------------------------

spring.jpa.hibernate.ddl-auto=update

# --------------------------------------------------
# JWT
# --------------------------------------------------

jwt.secret=43fGT!&lAR0%5ek<yETPyW86u_H0w9.V%0]?rJ451,zicU3}=j
jwt.expiration-minutes=60